# -*- coding: utf-8 -*-
"""lstm_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yCfQl3iGmTgvG9-2Gi1FCRE8WfnSX1d

# Import Libraries
"""

import numpy as np
import pandas as pd

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Dense, SpatialDropout1D
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

"""# Load Data"""

df = pd.read_csv(r'/content/all_tickets_processed_improved_v3.csv')

"""# Text Preprocessing"""

import string

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    #convert all to lowercase
    text = text.lower()

    # remove punctuations
    text = text.translate(str.maketrans('', '', string.punctuation))

    # tokenization
    tokens = word_tokenize(text)

    final = []

    # remove stopwords

    for token in tokens:
        if token not in stop_words:
            final.append(token)



    # lemmatization
    lemmatized = [lemmatizer.lemmatize(token) for token in final]



    return  lemmatized #  to use with word2vec

"""Convert to sequence and add padding to make them all the same lenght"""

tokenizer = Tokenizer()

x = df['Document'].apply(preprocess_text)
tokenizer.fit_on_texts(x)
sequences = tokenizer.texts_to_sequences(x)
max_seq_len = max(len(x) for x in sequences)
x = pad_sequences(sequences, maxlen=max_seq_len)

"""Encode the target feature"""

y = df['Topic_group']

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y = to_categorical(y)

"""# Split Data"""

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

"""# RNN"""

vocab_size = len(tokenizer.word_index) +1
num_of_classes = y.shape[1]
print(vocab_size)
print(num_of_classes)

y.shape

"""Model Structure"""

rnn_model = Sequential(
    [Embedding(input_dim=vocab_size, output_dim=100, input_length=max_seq_len),
    SpatialDropout1D(0.2),
    SimpleRNN(128),
    Dense(num_of_classes, activation='softmax')]
)

rnn_model.compile(optimizer='adam', loss= 'categorical_crossentropy', metrics=['accuracy'])

"""Callbacks Initialization"""

callbacks = [
    EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=2, min_lr=0.001)
]

rnn_history =rnn_model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2, callbacks=callbacks)

rnn_loss, rnn_accuracy = rnn_model.evaluate(x_test, y_test)

"""Evaluating the Model"""

y_pred_rnn = rnn_model.predict(x_test)
y_pred_classes_rnn = np.argmax(y_pred_rnn, axis=1)      # get predicted class index
y_test_classes_rnn = np.argmax(y_test, axis=1)       # get true class index

print(classification_report(y_test_classes_rnn, y_pred_classes_rnn, target_names=label_encoder.classes_))

"""# LSTM

Model Structure
"""

lstm_model = Sequential(
    [Embedding(input_dim=vocab_size, output_dim=100, input_length=max_seq_len),
    SpatialDropout1D(0.2),
    LSTM(128),
    Dense(num_of_classes, activation='softmax')]
)

lstm_model.compile(optimizer='adam', loss= 'categorical_crossentropy', metrics=['accuracy'])

lstm_history =lstm_model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2, callbacks=callbacks)

lstm_loss, lstm_accuracy = lstm_model.evaluate(x_test, y_test)

"""Evaluating the Model"""

y_pred_lstm = lstm_model.predict(x_test)
y_pred_classes_lstm = np.argmax(y_pred_lstm, axis=1)      # get predicted class index
y_test_classes_lstm = np.argmax(y_test, axis=1)       # get true class index

print(classification_report(y_test_classes_lstm, y_pred_classes_lstm, target_names=label_encoder.classes_))

"""# Save the Model"""

lstm_model.save('lstm_model.h5')